### ISSUE TITLE
Getting an exit code 100: virtualenv error on build

### ISSUE THREAD

**Issue by scuerda** [miguelgrinberg/slam#10]
I'm getting a few issues on build/deploy:

When running `slam build` or `slam deploy`, I get the following error:

```
Building lambda package...
b"Using base prefix '/usr/local/bin/../Cellar/python3/3.6.2/bin/../Frameworks/Python.framework/Versions/3.6'\nNew python executable in /Users/Work/Projects/test-slam-api/.slam/venv/bin/python3\nAlso creating executable in /Users/Work/Projects/test-slam-api/.slam/venv/bin/python\nERROR: The executable /Users/Work/Projects/test-slam-api/.slam/venv/bin/python3 is not functioning\nERROR: It thinks sys.prefix is '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6' (should be '/Users/scuerda/Work/Projects/OTHER/birth-navigation/births-api/.slam/venv')\nERROR: virtualenv is not compatible with this system or executable\n"
Runtime error: Command failed with exit code 100.
See file slam_error.log for additional details.
```

```
2017-09-06 13:32:39,422 - slam - ERROR - [merry] Exception caught
Traceback (most recent call last):
  File "/Users/Work/Projects/test-slam-api/venv/lib/python3.6/site-packages/merry.py", line 26, in wrapper
    ret = f(*args, **kwargs)
  File "/Users/Work/Projects/test-slam-api/venv/lib/python3.6/site-packages/climax.py", line 194, in wrapper
    ctx = func(**filtered_args)
  File "/Users/Work/Projects/test-slam-api/venv/lib/python3.6/site-packages/slam/cli.py", line 321, in build
    package = _build(config, rebuild_deps=rebuild_deps)
  File "/Users/Work/Projects/test-slam-api/venv/lib/python3.6/site-packages/slam/cli.py", line 235, in _build
    _run_command('virtualenv .slam/venv')
  File "/Users/Work/Projects/test-slam-api/venv/lib/python3.6/site-packages/slam/cli.py", line 173, in _run_command
    proc.returncode)))
RuntimeError: Command failed with exit code 100.
```

I'm guessing that this is just an upstream issue with homebrew and how it's playing with the cli tools, but I might be missing something?

**Comment by scuerda** [comment]
Can confirm that this was homebrew related. I ditched my homebrew 3.6.2 and switched to pyenv. Everything worked as expected! Thanks for your hard work on this!
